-- Create Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  emoji TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Seed Data for Categories
INSERT INTO categories (name, emoji) VALUES
  ('Hamburguesas', '🍔'),
  ('Pizza', '🍕'),
  ('Sushi', '🍣'),
  ('Asiática', '🍜'),
  ('Mexicana', '🌮'),
  ('Café & Postres', '☕'),
  ('Saludable', '🥗'),
  ('Bebidas', '🍹')
ON CONFLICT (name) DO NOTHING;

-- Modify Restaurants Table
-- Add category_id column
ALTER TABLE restaurants
ADD COLUMN IF NOT EXISTS category_id BIGINT;

-- Add Foreign Key Constraint
ALTER TABLE restaurants
ADD CONSTRAINT fk_restaurant_category
FOREIGN KEY (category_id)
REFERENCES categories(id)
ON DELETE SET NULL;

-- Optional: Create an index for faster filtering
CREATE INDEX IF NOT EXISTS idx_restaurants_category_id ON restaurants(category_id);

-- Migration Note:
-- You will need to update existing restaurant records to set the category_id based on the old 'cuisine_type' column.
-- Example:
-- UPDATE restaurants SET category_id = (SELECT id FROM categories WHERE name = 'Hamburguesas') WHERE cuisine_type ILIKE '%burger%';
