-- Create table for user movements (transactions)
CREATE TABLE IF NOT EXISTS movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  amount INTEGER NOT NULL, -- Negative for spend, positive for earn
  description TEXT,
  type TEXT CHECK (type IN ('earn', 'spend')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE movements ENABLE ROW LEVEL SECURITY;

-- Policy for users to view their own movements
CREATE POLICY "Users can view their own movements" ON movements
  FOR SELECT USING (auth.uid() = user_id);

-- Policy for users to insert their own movements (e.g., when spending points)
CREATE POLICY "Users can insert their own movements" ON movements
  FOR INSERT WITH CHECK (auth.uid() = user_id);
