-- Create menu_items table
CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id BIGINT REFERENCES restaurants(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  image_url TEXT,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public menu_items are viewable by everyone." ON menu_items
  FOR SELECT USING (true);

-- Insert sample menu items for Burger King (ID 1)
INSERT INTO menu_items (restaurant_id, name, description, price, image_url, category) VALUES
(1, 'Whopper Menu', 'A la parrilla sabe mejor. Incluye patatas y bebida.', 9.50, 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&q=80', 'Popular'),
(1, 'Long Chicken', 'Pollo crujiente en pan largo con mayonesa.', 8.20, 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80', 'Hamburguesas'),
(1, 'Nuggets x9', 'Crujientes nuggets de pollo con salsa a elegir.', 5.50, 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80', 'Entrantes');

-- Insert sample menu items for Sushi Master (ID 2)
INSERT INTO menu_items (restaurant_id, name, description, price, image_url, category) VALUES
(2, 'Salmon Roll', '8 piezas de roll de salmón fresco y aguacate.', 12.00, 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80', 'Sushi'),
(2, 'Sashimi Mix', 'Variado de sashimi de atún y salmón.', 15.50, 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&q=80', 'Sashimi'),
(2, 'Miso Soup', 'Sopa tradicional japonesa.', 4.00, 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80', 'Entrantes');

-- Insert sample menu items for Pizza Hut (ID 3)
INSERT INTO menu_items (restaurant_id, name, description, price, image_url, category) VALUES
(3, 'Pepperoni Feast', 'Doble pepperoni y extra queso.', 13.90, 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&q=80', 'Pizzas'),
(3, 'Margarita', 'Clásica con tomate y mozzarella.', 10.00, 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80', 'Pizzas');

-- Insert sample menu items for Taco Bell (ID 4)
INSERT INTO menu_items (restaurant_id, name, description, price, image_url, category) VALUES
(4, 'Crunchy Taco Supreme', 'Taco crujiente con carne, lechuga y queso.', 2.50, 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80', 'Tacos'),
(4, 'Burrito Bowl', 'Arroz, frijoles, carne y vegetales.', 8.90, 'https://images.unsplash.com/photo-1563583279-d5c2f0f8c926?w=800&q=80', 'Bowls');

-- Insert sample menu items for Indian Spice (ID 5)
INSERT INTO menu_items (restaurant_id, name, description, price, image_url, category) VALUES
(5, 'Chicken Tikka Masala', 'Pollo marinado en salsa de especias cremosa.', 14.50, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80', 'Curry'),
(5, 'Naan Bread', 'Pan indio tradicional.', 3.00, 'https://images.unsplash.com/photo-1610192244261-3f33de3f5501?w=800&q=80', 'Acompañantes');

-- Insert sample menu items for Healthy Greens (ID 6)
INSERT INTO menu_items (restaurant_id, name, description, price, image_url, category) VALUES
(6, 'Caesar Salad', 'Lechuga romana, picatostes, parmesano y salsa césar.', 9.00, 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800&q=80', 'Ensaladas'),
(6, 'Quinoa Bowl', 'Quinoa con aguacate, tomate y huevo.', 11.50, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80', 'Bowls');
